nodeLinker: pnp

# https://yarnpkg.com/getting-started/migration#troubleshooting
packageExtensions:
  "@types/react@*":
    dependencies:
      "prop-types": "*"
      "react": "*"
      "scheduler": "*"
  "@types/react-dom@*":
    dependencies:
      "react": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

pnpMode: loose

yarnPath: .yarn/releases/yarn-3.6.1.cjs
