nodeLinker: pnp

# https://yarnpkg.com/getting-started/migration#troubleshooting
packageExtensions:
  "@emotion/react@*":
    dependencies:
      "eslint-import-resolver-node": "*"
  "@pkgr/utils@*":
    dependencies:
      "react": "*"
  "@rushstack/eslint-patch@*":
    dependencies:
      "@eslint/eslintrc": "*"
  "@trpc/client@*":
    dependencies:
      "@trpc/server": "*"
  "@trpc/react-query@*":
    dependencies:
      "@trpc/server": "*"
  "@types/react@*":
    dependencies:
      "prop-types": "*"
      "react": "*"
      "scheduler": "*"
  "@types/react-dom@*":
    dependencies:
      "react": "*"
  "debug@*":
    dependencies:
      "supports-color": "*"
  "eslint@*":
    dependencies:
      "@typescript-eslint/parser": "*"
  "eslint-config-next@*":
    dependencies:
      "next": "*"
  "eslint-module-utils@*":
    dependencies:
      "eslint-import-resolver-typescript": "*"
  "next@*":
    dependencies:
      "@eslint/eslintrc": "*"
  "superjson@*":
    dependencies:
      "eslint-import-resolver-node": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

pnpMode: loose

yarnPath: .yarn/releases/yarn-3.6.1.cjs
